image: maven:3-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  GIT_STRATEGY: "clone"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/sila-db"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "admin"
  POSTGRES_DB: sila-db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin

cache:
  paths:
    - .m2/

stages:
  - test

services:
  - name: postgres:latest
    alias: postgres
    command: ["postgres", "-c", "listen_addresses='*'"]

test-backend:
  stage: test
  script:
    - cd backend
    - mvn -B clean install -Dspring.profiles.active=test
  variables:
    SPRING_PROFILES_ACTIVE: "test" 
    SPRING_DATASOURCE_URL: ""
    SPRING_DATASOURCE_USERNAME: ""
    SPRING_DATASOURCE_PASSWORD: ""

test-frontend:
  image: node:lts
  stage: test
  script:
    - cd frontend && npm install && npx ng build

test-datascience:
    image: python:3.13
    stage: test
    before_script:
      - cd datascience
      - pip install --upgrade pip
      - pip install -r requirements.txt
    script:
      - python -m unittest discover -s test -p "test_*.py"